project

diff --git a/week9/1_ex9_jenkinsfile b/week9/1_ex9_jenkinsfile
--- a/week9/1_ex9_jenkinsfile
+++ b/week9/1_ex9_jenkinsfile
@@ -62,46 +62,50 @@ node(POD_LABEL) {
         }
 
 
+
     stage('check calc image for div') {
-	sh '''
+        sh '''
 
-	cd $WORKSPACE/week9/
+        cd $WORKSPACE/week9/
 
-	## update image to dlambrig/hello-kaniko:0.5
-	echo 'update image to dlambrig/hello-kaniko:0.5 which has sum but no div'
-	./kubectl set image deployment/calculator-deployment calculator=dlambrig/hello-kaniko:0.5 -n staging
-	sleep 30
+        ## update image to dlambrig/hello-kaniko:0.5
+        echo 'update image to dlambrig/hello-kaniko:0.5 which has sum but no div'
+        ./kubectl set image deployment/calculator-deployment calculator=dlambrig/hello-kaniko:0.5 -n staging
+        sleep 30
 
-	echo 'sum test'
-	test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 8 && echo 'pass' || echo 'fail'
-	test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 7 && echo 'pass' || echo 'fail'
+        echo 'sum test'
+        ./kubectl get svc
+        test $(curl -s calculator-service.staging.svc.cluster.local:8080/sum?a=6\\&b=2) -eq 8 && echo 'pass' || echo 'fail'
+        test $(curl -s calculator-service.staging.svc.cluster.local:8080/sum?a=6\\&b=2) -eq 7 && echo 'pass' || echo 'fail'
 
-	echo 'division test'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo 'pass' || echo 'fail'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 4 && echo 'pass' || echo 'fail'
+        # echo 'division test'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo 'pass' || echo 'fail'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 4 && echo 'pass' || echo 'fail'
 
-	echo 'division by zero test'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=0) -eq 3 && echo 'pass' || echo 'fail'
+        # echo 'division by zero test'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=0) -eq 3 && echo 'pass' || echo 'fail'
 
 
-	## update image to dlambrig/hello-kaniko:1.0
-	echo 'update image to dlambrig/hello-kaniko:1.0 which has sum and div'
-	./kubectl set image deployment/calculator-deployment calculator=dlambrig/hello-kaniko:1.0 -n staging
-	sleep 30
+        # ## update image to dlambrig/hello-kaniko:1.0
+        # echo 'update image to dlambrig/hello-kaniko:1.0 which has sum and div'
+        # ./kubectl set image deployment/calculator-deployment calculator=dlambrig/hello-kaniko:1.0 -n staging
+        # sleep 30
 
-	echo 'sum test'
-	test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 8 && echo 'pass' || echo 'fail'
-	test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 7 && echo 'pass' || echo 'fail'
+        # echo 'sum test'
+        # test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 8 && echo 'pass' || echo 'fail'
+        # test $(curl -s calculator-service:8080/sum?a=6\\&b=2) -eq 7 && echo 'pass' || echo 'fail'
 
-	echo 'division test'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo 'pass' || echo 'fail'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 4 && echo 'pass' || echo 'fail'
+        # echo 'division test'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo 'pass' || echo 'fail'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=2) -eq 4 && echo 'pass' || echo 'fail'
 
-	echo 'division by zero test'
-	test $(curl -s calculator-service:8080/div?a=6\\&b=0) -eq 3 && echo 'pass' || echo 'fail'
-	'''
+        # echo 'division by zero test'
+        # test $(curl -s calculator-service:8080/div?a=6\\&b=0) -eq 3 && echo 'pass' || echo 'fail'
+        '''
 
-	}
+        }
+
+
        }
      }
 
